Repository adobe/spacecat-api-service, pull requests merged in 2024-08, with the labels that each got.

#434 fix: switch to spacecat coralogix for site detection
  docs/index.html
  docs/openapi/hooks-api.yaml
  src/controllers/hooks.js
  test/controllers/hooks.test.js
Labels: bug

#439 docs: generic schema for experimentation opportunities
  docs/index.html
  docs/openapi/schemas.yaml
Labels: documentation

#442 feat: add scopes in the import controller
  docs/openapi/tools-api.yaml
  src/controllers/import.js
  src/index.js
  src/support/import-supervisor.js
  test/controllers/import.test.js
Labels: enhancement

#455 docs: add costs and broken backlinks audit result schemas and examples
  .github/pull_request_template.md
  docs/index.html
  docs/openapi/audit-api.yaml
  docs/openapi/examples.yaml
  docs/openapi/schemas.yaml
Labels: documentation

#449 fix: use metrics-store and s3 wrapper from shared
  package-lock.json
  package.json
  src/controllers/sites.js
  src/support/metrics-store.js
  src/support/s3.js
  test/controllers/sites.test.js
  test/support/metrics-store.test.js
  test/support/s3.test.js
Labels: tech debt, seo

#458 chore(deps): Update to node 20.16.0 (LTS)
  .circleci/config.yml
  .npmrc
  package-lock.json
  package.json
Labels: enhancement

#448 feat: introducing structured-data audit result type
  docs/index.html
  docs/openapi/schemas.yaml
Labels: documentation

#467 docs: cwv api result schema
  docs/index.html
  docs/openapi/schemas.yaml
Labels: documentation

#471 fix(site-detection): ignore domains
  src/controllers/hooks.js
Labels: enhancement

#472 fix(site-detection): ignore domains
  src/controllers/hooks.js
Labels: enhancement
