Repository adobe/spacecat-api-service, pull requests merged in 2024-11, with the labels that each got.

#562 fix: engine spec, dynamo query
  package-lock.json
  package.json
Labels: bug

#552 fix: add recommendations (ex: guidance) information to the experimentation opportunity object
  docs/index.html
  docs/openapi/schemas.yaml
Labels: enhancement

#569 feat: Build an API to generate API keys for the importer
  docs/index.html
  docs/openapi/schemas.yaml
  docs/openapi/tools-api.yaml
  src/controllers/api-key.js
  src/dto/api-key.js
  src/utils/constants.js
  test/controllers/api-key.test.js
Labels: enhancement

#586 fix: update deps
  package-lock.json
  package.json
Labels: enhancement

#584 fix: get site command slack error
  package-lock.json
  src/utils/slack/base.js
  test/utils/slack/base.test.js
Labels: bug

#556 feat: HTTP API specification for opportunities, suggestions
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/examples.yaml
  docs/openapi/parameters.yaml
  docs/openapi/schemas.yaml
  docs/openapi/site-opportunities.yaml
Labels: documentation

#591 fix: udpate deps
  package-lock.json
  package.json
Labels: enhancement

#597 fix(api-spec): fix schema and example of request body of create suggestions
  docs/index.html
  docs/openapi/examples.yaml
  docs/openapi/schemas.yaml
Labels: documentation
