Repository adobe/spacecat-api-service, pull requests merged in 2024-12, with the labels that each got.

#574 docs(api): cwv schema changes to support groups and site metrics
  docs/index.html
  docs/openapi/schemas.yaml
Labels: documentation

#643 fix(deps): update data access
  package-lock.json
  package.json
Labels: bug

#645 chore: switch to gh-actions
  .circleci/config.yml
  .github/workflows/ci.yaml
  package.json
Labels: enhancement
