Repository adobe/spacecat-api-service, pull requests merged in 2024-01, with the labels that each got.

#102 fix: api docs and update properties
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/audit-api.yaml
  docs/openapi/audits-api.yaml
  docs/openapi/parameters.yaml
  docs/openapi/redocly-config.yaml
  docs/openapi/responses.yaml
  docs/openapi/schemas.yaml
  docs/openapi/site-api.yaml
  docs/openapi/sites-api.yaml
  docs/openapi/sites-query-api.yaml
  docs/openapi/trigger-api.yaml
  src/controllers/sites.js
  src/support/slack/commands/add-repo.js
  src/utils/validations.js
  test/controllers/sites.test.js
Labels: bug, documentation

#107 fix: update to node 20, deps
  .circleci/config.yml
  package-lock.json
  package.json
  renovate.json5
Labels: enhancement

#111 chore: organization api spec
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/organization-api.yaml
  docs/openapi/organizations-api.yaml
  docs/openapi/parameters.yaml
  docs/openapi/responses.yaml
  docs/openapi/schemas.yaml
  docs/openapi/sites-api.yaml
Labels: documentation

#119 feat: organizations API
  src/controllers/organizations.js
  src/dto/organization.js
  src/index.js
  src/routes/index.js
  test/controllers/organizations.test.js
  test/routes/index.test.js
Labels: enhancement

#124 chore(docs): site list responses, with latest audit (#112)
  docs/index.html
  docs/openapi/schemas.yaml
  docs/openapi/sites-api.yaml
Labels: bug

#121 chore: initial event hook and Slack API spec
  docs/openapi/api.yaml
  docs/openapi/event-api.yaml
  docs/openapi/organization-api.yaml
  docs/openapi/parameters.yaml
  docs/openapi/responses.yaml
  docs/openapi/schemas.yaml
Labels: documentation, enhancement

#101 feat: 404 report for customers
  src/controllers/trigger/notfound.js
  test/controllers/trigger/notfound.test.js
Labels: enhancement
