Repository adobe/spacecat-api-service, pull requests merged in 2024-09, with the labels that each got.

#480 fix: make ignored (sub-/domains) configurable
  src/controllers/hooks.js
  test/controllers/hooks.test.js
Labels: enhancement

#482 chore: migrate renovate secrets
  default.json
Labels: bug

#487 Use multipart/form-data content type to support upload of custom import.js
  .eslintignore
  docs/index.html
  docs/openapi/responses.yaml
  docs/openapi/schemas.yaml
  docs/openapi/tools-api.yaml
  package-lock.json
  package.json
  src/controllers/import.js
  src/index.js
  src/support/import-supervisor.js
  src/support/multipart-form-data.js
  test/controllers/fixtures/sample-import-script.js
  test/controllers/import.test.js
  test/index.test.js
  test/support/fixtures/sample-file.txt
  test/support/multipart-form-data.test.js
Labels: bug

#494 fix: Update API docs to match implementation
  docs/index.html
  docs/openapi/schemas.yaml
Labels: documentation

#508 feat: SITES-23133 [Importer] Report on the progress of a import job via a new jobs endpoint
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/schemas.yaml
  docs/openapi/tools-api.yaml
  package-lock.json
  package.json
  src/controllers/import.js
  src/dto/import-job.js
  src/routes/index.js
  src/support/import-supervisor.js
  test/controllers/import.test.js
  test/routes/index.test.js
Labels: enhancement

#511 feat: Restrict importing URLs which are not allowlisted (by domain) for the API key
  package-lock.json
  package.json
  src/controllers/import.js
  test/controllers/import.test.js
Labels: enhancement
