Repository adobe/spacecat-api-service, pull requests merged in 2024-07, with the labels that each got.

#382 fix: temporary back fill of hlx config
  src/controllers/hooks.js
  test/controllers/hooks.test.js
Labels: enhancement

#384 fix: allow authorization header
  src/index.js
  test/index.test.js
Labels: bug

#385 fix: prevent unfurl for hlx config
  src/controllers/hooks.js
  src/utils/slack/base.js
  test/controllers/hooks.test.js
  test/support/slack/actions/slack-fixtures.js
Labels: bug

#388 fix: update hlx config when changed
  package-lock.json
  package.json
  src/controllers/hooks.js
  src/dto/site.js
  test/controllers/hooks.test.js
Labels: bug

#389 fix: hlx config updates too much
  src/controllers/hooks.js
  test/controllers/hooks.test.js
Labels: bug

#390 fix: reduce hlx 4 config
  src/controllers/hooks.js
  test/controllers/hooks.test.js
Labels: bug

#392 fix: suppress unnecessary slack noise coming from hlx config updates
  src/controllers/hooks.js
  test/controllers/hooks.test.js
Labels: enhancement

#395 feat: add urlCount to the data access layer
  package-lock.json
  package.json
  src/support/import-supervisor.js
Labels: enhancement

#400 fix: Include x-import-api-key header in Access-Control-Allow-Headers
  src/index.js
  test/index.test.js
Labels: bug

#401 feat: Enforce a maximum of 1 running import job per API key
  src/support/import-supervisor.js
  test/controllers/import.test.js
Labels: enhancement

#403 feat: Enforce a maximum number of URLs that can be imported per job
  src/controllers/import.js
  test/controllers/import.test.js
Labels: enhancement

#409 chore: fix local development
  package-lock.json
  package.json
  test/dev/server.mjs
Labels: tech debt

#411 fix: update node 20.15.1
  .circleci/config.yml
  .husky/pre-commit
  package-lock.json
  src/support/auth/handlers/ims.js
  test/support/auth/handlers/ims.test.js
Labels: enhancement

#414 fix: configuration api endpoints
  src/dto/configuration.js
  test/controllers/configurations.test.js
Labels: bug

#415 feat: Import API endpoint updates
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/schemas.yaml
  docs/openapi/tools-api.yaml
  src/routes/index.js
  test/routes/index.test.js
Labels: enhancement

#419 chore(docs): scraper prototype API
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/responses.yaml
  docs/openapi/schemas.yaml
  docs/openapi/scrape-api.yaml
Labels: enhancement

#410 feat: canonical url audit
  docs/index.html
  docs/openapi/schemas.yaml
  src/controllers/trigger.js
  src/controllers/trigger/canonical.js
  test/controllers/trigger/canonical.test.js
Labels: enhancement

#420 fix: move auth code to http-utils
  package-lock.json
  package.json
  src/index.js
  src/support/auth/auth-info.js
  src/support/auth/auth-wrapper.js
  src/support/auth/authentication-manager.js
  src/support/auth/errors/not-authenticated.js
  src/support/auth/handlers/abstract.js
  src/support/auth/handlers/config/ims-stg.js
  src/support/auth/handlers/config/ims.js
  src/support/auth/handlers/ims.js
  src/support/auth/handlers/legacy-api-key.js
  src/support/auth/readme.md
  test/fixtures/auth/ims/private_key.pem
  test/fixtures/auth/ims/public-jwks.js
  test/fixtures/auth/ims/public_key.pem
  test/fixtures/auth/ims/readme.md
  test/support/auth/auth-wrapper.test.js
  test/support/auth/authentication-manager.test.js
  test/support/auth/handlers/abstract.test.js
  test/support/auth/handlers/ims.test.js
  test/support/auth/handlers/legacy-api-keys.test.js
Labels: enhancement
