Repository adobe/spacecat-api-service, pull requests merged in 2024-05, with the labels that each got.

#298 feat(api): add api spec for exposing site metrics by source and implementation
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/parameters.yaml
  docs/openapi/schemas.yaml
  docs/openapi/site-metrics-api.yaml
  docs/openapi/site-top-pages-api.yaml
  package-lock.json
  package.json
  src/controllers/sites.js
  src/routes/index.js
  src/support/metrics-store.js
  test/controllers/sites.test.js
  test/routes/index.test.js
  test/support/metrics-store.test.js
Labels: seo

#313 fix: message format for exp candidates
  src/support/slack/commands/get-exp-candidates.js
  src/support/utils.js
Labels: bug

#314 feat: introduce google authentication endpoint
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/auth-api.yaml
Labels: enhancement
