Repository adobe/spacecat-api-service, pull requests merged in 2024-03, with the labels that each got.

#136 feat: sitemap detection audit
  src/controllers/trigger.js
  src/controllers/trigger/sitemap.js
  test/controllers/trigger/sitemap.test.js
Labels: enhancement

#193 chore: configurations api
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/configuration-api.yaml
  docs/openapi/configurations-api.yaml
  docs/openapi/responses.yaml
  docs/openapi/schemas.yaml
Labels: documentation, enhancement

#198 feat: get and update configurations
  package-lock.json
  package.json
  src/controllers/configuration.js
  src/dto/configuration.js
  src/index.js
  src/routes/index.js
  src/utils/configMerge.js
  test/controllers/configurations.test.js
  test/routes/index.test.js
  test/utils/configMerge.test.js
Labels: enhancement

#199 fix: configure /event/fulfillment as one of the ADMIN_ENDPOINTS
  docs/openapi/event-api.yaml
  src/support/auth.js
  test/support/auth.test.js
Labels: bug

#200 feat: Endpoints for querying SpaceCat organization details by IMS org ID
  README.md
  src/controllers/organizations.js
  src/index.js
  src/routes/index.js
  test/controllers/organizations.test.js
  test/routes/index.test.js
Labels: enhancement

#213 feat(add-site): auto detect site type in add site command
  src/controllers/hooks.js
  src/support/slack/commands/add-site.js
  src/support/utils.js
  test/controllers/hooks.test.js
  test/support/slack/commands/add-site.test.js
Labels: enhancement

#224 feat: filter friends and family organization from get all sites command
  src/support/slack/commands/get-sites.js
  test/support/slack/commands/get-sites.test.js
Labels: enhancement

#244 fix: remove config update
  docs/index.html
  docs/openapi/configuration-api.yaml
  docs/openapi/schemas.yaml
  src/controllers/configuration.js
  src/utils/configMerge.js
  test/controllers/configurations.test.js
  test/utils/configMerge.test.js
Labels: bug
