Repository adobe/spacecat-api-service, pull requests merged in 2024-04, with the labels that each got.

#188 feat: analytics site integration API spec
  docs/openapi/api.yaml
  docs/openapi/examples.yaml
  docs/openapi/hooks-api.yaml
  docs/openapi/schemas.yaml
Labels: analytics

#264 fix: docs linting, openapi version upgrade and multiple examples support
  .circleci/config.yml
  docs/openapi/api.yaml
  docs/openapi/schemas.yaml
Labels: bug

#266 fix: remove lhs trigger handler
  src/controllers/trigger.js
  src/controllers/trigger/lhs.js
  test/controllers/trigger/lhs.test.js
Labels: enhancement

#248 fix: slack format messages
  src/support/slack/commands/add-repo.js
  src/support/slack/commands/add-site.js
  src/support/slack/commands/get-site.js
  src/support/slack/commands/set-live-status.js
  src/utils/slack/base.js
  test/support/slack/commands/add-repo.test.js
  test/utils/slack/base.test.js
Labels: bug
