Repository adobe/spacecat-api-service, pull requests merged in 2025-05, with the labels that each got.

#893 docs: async scrape endpoint
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/preflight-api.yaml
  docs/openapi/schemas.yaml
  docs/openapi/scrape-api.yaml
Labels: documentation

#892 docs: HTTP API specification for scraped content
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/parameters.yaml
  docs/openapi/schemas.yaml
  docs/openapi/scrape-api.yaml
  docs/openapi/site-scrape-api.yaml
Labels: documentation

#901 feat: Slack command for internal reports
  src/support/slack/commands.js
  src/support/slack/commands/run-internal-report.js
  src/support/utils.js
  test/support/slack/commands/run-internal-report.test.js
Labels: enhancement, automation

#918 docs: get file by s3 object key
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/file-api.yaml
  docs/openapi/schemas.yaml
  docs/openapi/site-scrape-api.yaml
  docs/openapi/tools-api.yaml
Labels: documentation

#923 feat: mcp prototype server
  package-lock.json
  package.json
  src/controllers/mcp.js
  src/index.js
  src/mcp/http-adapter.js
  src/mcp/registry.js
  src/mcp/registry/resources/audits.js
  src/mcp/registry/resources/sites.js
  src/mcp/registry/tools/audits.js
  src/mcp/registry/tools/sites.js
  src/mcp/registry/tools/utils.js
  src/mcp/server.js
  src/routes/index.js
  src/utils/jsonrpc.js
  src/utils/validations.js
  test/controllers/mcp.test.js
  test/routes/index.test.js
  test/utils/jsonrpc.test.js
  test/utils/validations.test.js
Labels: enhancement

#932 feat: add scraper mcp tools support
  src/index.js
  src/mcp/registry.js
  src/mcp/registry/resources/scrape-content.js
  src/mcp/registry/tools/scrape-content.js
  src/utils/jsonrpc.js
  test/controllers/mcp.test.js
Labels: enhancement

#944 fix: sse related errors by not allowing get method
  src/controllers/mcp.js
  src/routes/index.js
  test/routes/index.test.js
Labels: bug

#943 fix: update description for getSiteByBaseURLTool
  src/mcp/registry/tools/sites.js
Labels: bug, documentation
