Repository adobe/spacecat-api-service, pull requests merged in 2025-06, with the labels that each got.

#952 docs: add MCP Cursor Custom Mode
  docs/cursor/add-mcp-tool.prompt
  docs/cursor/readme.md
Labels: documentation

#954 feat: add mcp endpoint to return all audits for historical analysis
  src/mcp/registry/resources/audits.js
  src/mcp/registry/tools/audits.js
  test/controllers/mcp.test.js
Labels: enhancement

#976 feat: slack command to check for enabled and disabled audits for a site
  src/support/slack/commands.js
  src/support/slack/commands/get-site-audits.js
  test/support/slack/commands/get-site-audits.test.js
Labels: do not merge

#1022 feat: introduce authoring type in sites
  package-lock.json
  package.json
  src/controllers/preflight.js
  src/controllers/sites.js
  src/dto/site.js
  test/controllers/preflight.test.js
  test/controllers/sites.test.js
Labels: enhancement

#1027 Update docs for cdn config examples and fix test
  docs/index.html
  docs/openapi/schemas.yaml
  package-lock.json
  package.json
  test/controllers/sites.test.js
Labels: documentation
