Repository adobe/spacecat-api-service, pull requests merged in 2025-01, with the labels that each got.

#662 fix: Bump node version used by importer E2E test workflow
  .github/workflows/e2e-tests.yaml
Labels: bug

#667 fix: latest audits api response
  src/controllers/audits.js
  test/controllers/audits.test.js
Labels: bug

#668 fix: update deps
  package-lock.json
  package.json
  src/support/import-supervisor.js
Labels: bug

#670 fix: Import job progress endpoint
  src/support/import-supervisor.js
  test/controllers/import.test.js
Labels: bug

#675 fix: create site
  src/controllers/sites.js
  src/index.js
  src/support/slack/commands/add-site.js
  test/controllers/sites.test.js
  test/support/slack/commands/add-site.test.js
Labels: bug

#678 fix: getAllLatestForSite endpoint
  src/routes/index.js
Labels: bug

#500 docs: adjust endpoint to existent /sites/{siteId}/audits/latest
  docs/openapi/api.yaml
Labels: documentation

#681 fix: org invalid uuid
  package-lock.json
  package.json
  src/controllers/hooks.js
  src/controllers/organizations.js
  test/controllers/hooks.test.js
  test/controllers/organizations.test.js
  test/index.test.js
Labels: bug

#683 chore: api-doc for /scrape
  docs/index.html
  docs/openapi/schemas.yaml
Labels: documentation

#685 fix(deps): update to data-access-2.0.0
  package-lock.json
  package.json
  src/controllers/hooks.js
  src/controllers/import.js
  src/controllers/organizations.js
  src/controllers/sites.js
  src/controllers/trigger/apex.js
  src/controllers/trigger/backlinks.js
  src/controllers/trigger/canonical.js
  src/controllers/trigger/cwv.js
  src/controllers/trigger/organictraffic.js
  src/controllers/trigger/sitemap.js
  src/dto/configuration.js
  src/support/import-supervisor.js
  src/support/slack/actions/approve-site-candidate.js
  src/support/slack/actions/ignore-site-candidate.js
  src/support/slack/commands/add-site.js
  src/support/utils.js
  test/controllers/api-key.test.js
  test/controllers/audits.test.js
  test/controllers/configurations.test.js
  test/controllers/experiments.test.js
  test/controllers/import.test.js
  test/controllers/organizations.test.js
  test/controllers/sites.test.js
  test/controllers/slack.test.js
  test/controllers/trigger/backlinks.test.js
Labels: enhancement

#689 fix: config dto
  package-lock.json
  package.json
  src/dto/site.js
  test/controllers/import.test.js
  test/controllers/organizations.test.js
  test/controllers/sites.test.js
Labels: bug

#691 feat: add api endpoint to delete a suggestion
  docs/index.html
  docs/openapi/site-opportunities.yaml
  src/controllers/opportunities.js
  src/controllers/suggestions.js
  src/routes/index.js
  test/controllers/suggestions.test.js
  test/routes/index.test.js
Labels: enhancement

#692 fix: cpc 0 if no stored metrics
  src/controllers/sites.js
  test/controllers/sites.test.js
Labels: bug

#693 fix: prevent error on invalid uuid
  src/controllers/audits.js
  src/controllers/experiments.js
  src/controllers/opportunities.js
  src/controllers/organizations.js
  src/controllers/sites.js
  src/controllers/suggestions.js
  src/support/import-supervisor.js
  test/controllers/audits.test.js
  test/controllers/experiments.test.js
  test/controllers/import.test.js
  test/controllers/opportunities.test.js
  test/controllers/sites.test.js
  test/controllers/suggestions.test.js
Labels: bug

#696 fix: graceful handling for missing domain key
  docs/index.html
  docs/openapi/site-metrics-api.yaml
  src/controllers/sites.js
  test/controllers/sites.test.js
Labels: bug

#698 fix: find opportunity in removeSuggestion
  src/controllers/suggestions.js
  test/routes/index.test.js
Labels: bug

#702 fix: branch protection / npm cache
  .github/actions/configure-aws/action.yaml
  .github/actions/lint-test-coverage/action.yaml
  .github/actions/setup-node-npm/action.yaml
  .github/workflows/ci.yaml
  README.md
Labels: bug

#712 feat: introduce broken backlink suggestions
  docs/index.html
  docs/openapi/examples.yaml
  docs/openapi/schemas.yaml
Labels: enhancement
