Repository adobe/spacecat-api-service, pull requests merged in 2025-02, with the labels that each got.

#713 Feat: add broken internal links audit example and related schema definitions
  docs/index.html
  docs/openapi/audit-api.yaml
  docs/openapi/examples.yaml
  docs/openapi/schemas.yaml
Labels: enhancement

#742 feat(page-metrics): API to get page level metrics by page URL
  docs/index.html
  docs/openapi/api.yaml
  docs/openapi/configurations-sites-audits-api.yaml
  docs/openapi/parameters.yaml
  docs/openapi/schemas.yaml
  docs/openapi/site-metrics-api.yaml
  src/controllers/sites.js
  src/routes/index.js
  test/controllers/sites.test.js
  test/routes/index.test.js
Labels: documentation, enhancement, seo

#753 feat: add aem_ams to slack commands
  docs/index.html
  package-lock.json
  package.json
  src/support/slack/commands/add-site.js
  src/support/slack/commands/get-sites.js
  test/support/slack/commands/add-site.test.js
  test/support/slack/commands/get-sites.test.js
Labels: enhancement

#752 feat: update site name in site entity
  docs/index.html
  docs/openapi/schemas.yaml
  src/controllers/sites.js
  src/dto/site.js
  test/controllers/sites.test.js
Labels: enhancement

#758 fix: npm audit
  package-lock.json
Labels: bug

#760 docs(metrics): improve docs for metrics endpoints
  docs/index.html
  docs/openapi/parameters.yaml
  docs/openapi/site-metrics-api.yaml
Labels: documentation

#767 fix: temporarily disable role check
  src/support/slack/commands/run-import.js
  src/support/slack/commands/run-scrape.js
  test/support/slack/commands/run-scrape.test.js
Labels: bug

#769 fix: range may be undefined
  src/support/slack/commands/run-import.js
Labels: bug

#766 SITES-28578: implement onboard command
  package-lock.json
  package.json
  src/support/slack/commands/onboard.js
  src/utils/slack/base.js
  static/onboard/profiles.json
  test/support/slack/commands/onboard.test.js
  test/utils/slack/base.test.js
Labels: enhancement

#786 fix: org creation in onboard command
  src/support/slack/commands/onboard.js
  test/support/slack/commands/onboard.test.js
Labels: bug
